-- 门禁设备表
CREATE TABLE `acc_device` (
  `id` varchar(32) NOT NULL COMMENT '主键ID',
  `sn` varchar(100) NOT NULL COMMENT '设备序列号',
  `device_type` varchar(50) DEFAULT NULL COMMENT '设备类型 (acc, att, pos ...)',
  `device_name` varchar(200) DEFAULT NULL COMMENT '设备名称',
  `firmware_version` varchar(50) DEFAULT NULL COMMENT '固件版本',
  `push_version` varchar(50) DEFAULT NULL COMMENT '推送协议版本',
  `lock_count` int(11) DEFAULT NULL COMMENT '支持的锁数量',
  `reader_count` int(11) DEFAULT NULL COMMENT '支持的读头数量',
  `machine_type` int(11) DEFAULT NULL COMMENT '机器类型标识 (如101代表一体机)',
  `ip_address` varchar(50) DEFAULT NULL COMMENT 'IPv4地址',
  `gateway_ip` varchar(50) DEFAULT NULL COMMENT '网关IPv4地址',
  `net_mask` varchar(50) DEFAULT NULL COMMENT '子网掩码',
  `init_payload` text COMMENT '原始初始化请求载荷',
  `registry_payload` text COMMENT '原始注册载荷',
  `last_known_ip` varchar(50) DEFAULT NULL COMMENT '最后检测到的IPv4地址',
  `last_init_time` datetime DEFAULT NULL COMMENT '最后初始化握手时间',
  `last_registry_time` datetime DEFAULT NULL COMMENT '最后注册时间',
  `last_heartbeat_time` datetime DEFAULT NULL COMMENT '最后心跳时间',
  `status` varchar(50) DEFAULT NULL COMMENT '授权状态',
  `authorized` tinyint(1) DEFAULT '0' COMMENT '是否已授权',
  `registry_code` varchar(100) DEFAULT NULL COMMENT '注册码',
  `remark` varchar(500) DEFAULT NULL COMMENT '备注',
  `create_by` varchar(50) DEFAULT NULL COMMENT '创建人',
  `create_time` datetime DEFAULT NULL COMMENT '创建时间',
  `update_by` varchar(50) DEFAULT NULL COMMENT '更新人',
  `update_time` datetime DEFAULT NULL COMMENT '更新时间',
  PRIMARY KEY (`id`),
  UNIQUE KEY `uk_sn` (`sn`),
  KEY `idx_device_type` (`device_type`),
  KEY `idx_authorized` (`authorized`),
  KEY `idx_ip_address` (`ip_address`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='门禁设备表';
