CREATE TABLE `ipc_camera_device` (
  `id`                      varchar(32)  NOT NULL COMMENT 'Primary key',
  `create_by`               varchar(32)  DEFAULT NULL COMMENT 'Creator',
  `create_time`             datetime     DEFAULT NULL COMMENT 'Create time',
  `update_by`               varchar(32)  DEFAULT NULL COMMENT 'Updater',
  `update_time`             datetime     DEFAULT NULL COMMENT 'Update time',
  `device_name`             varchar(128) NOT NULL COMMENT 'Device name',
  `camera_type`             varchar(64)  DEFAULT NULL COMMENT 'Camera category',
  `vendor`                  varchar(64)  DEFAULT NULL COMMENT 'Vendor code',
  `username`                varchar(64)  DEFAULT NULL COMMENT 'RTSP username',
  `password`                varchar(128) DEFAULT NULL COMMENT 'RTSP password',
  `onvif_username`          varchar(128) DEFAULT NULL COMMENT 'ONVIF service username',
  `onvif_password`          varchar(128) DEFAULT NULL COMMENT 'ONVIF service password',
  `ip_address`              varchar(64)  NOT NULL COMMENT 'Camera IP or host',
  `port`                    varchar(16)  DEFAULT '554' COMMENT 'RTSP port',
  `stream_id`               varchar(128) DEFAULT NULL COMMENT 'ZLM stream id',
  `rtsp_transport`          varchar(16)  DEFAULT 'tcp' COMMENT 'RTSP transport',
  `on_demand`               tinyint(1)   DEFAULT 1 COMMENT 'Pull on demand flag',
  `rtsp_path`               varchar(128) DEFAULT '/h264' COMMENT 'RTSP path',
  `hls_url`                 varchar(255) DEFAULT NULL COMMENT 'HLS play url',
  `flv_url`                 varchar(255) DEFAULT NULL COMMENT 'HTTP-FLV play url',
  `webrtc_api`              varchar(255) DEFAULT NULL COMMENT 'WebRTC play api',
  `parent_id`               varchar(32)  DEFAULT NULL COMMENT 'Parent device id when representing an NVR channel',
  `role`                    varchar(32)  DEFAULT 'camera' COMMENT 'Device role (nvr/channel/camera)',
  `channel_index`           int          DEFAULT NULL COMMENT 'Channel index for NVR channel devices',
  `source_token`            varchar(128) DEFAULT NULL COMMENT 'ONVIF source token',
  `profile_token`           varchar(128) DEFAULT NULL COMMENT 'Selected ONVIF profile token',
  `profile_kind`            varchar(32)  DEFAULT NULL COMMENT 'ONVIF profile kind',
  `profile_name`            varchar(128) DEFAULT NULL COMMENT 'ONVIF profile name',
  `onvif_rtsp_url`          varchar(255) DEFAULT NULL COMMENT 'RTSP url discovered from ONVIF service',
  `media_version`           int          DEFAULT NULL COMMENT 'ONVIF media service version',
  `channel_count`           int          DEFAULT NULL COMMENT 'Total channels reported by ONVIF service',
  `state_hash`              varchar(128) DEFAULT NULL COMMENT 'ONVIF device state hash',
  `device_manufacturer`     varchar(128) DEFAULT NULL COMMENT 'ONVIF device manufacturer',
  `device_model`            varchar(128) DEFAULT NULL COMMENT 'ONVIF device model',
  `device_firmware_version` varchar(128) DEFAULT NULL COMMENT 'ONVIF device firmware version',
  `device_serial_number`    varchar(128) DEFAULT NULL COMMENT 'ONVIF device serial number',
  `device_hardware_id`      varchar(128) DEFAULT NULL COMMENT 'ONVIF device hardware id',
  `capabilities_json`       text         COMMENT 'Serialized ONVIF capabilities payload',
  `raw_onvif_payload`       longtext     COMMENT 'Full ONVIF payload snapshot',
  PRIMARY KEY (`id`),
  UNIQUE KEY `uk_ipc_camera_device_stream_id` (`stream_id`),
  KEY `idx_ipc_camera_device_ip_port` (`ip_address`, `port`),
  KEY `idx_ipc_camera_device_parent` (`parent_id`),
  KEY `idx_ipc_camera_device_role` (`role`),
  KEY `idx_ipc_camera_device_source` (`source_token`),
  CONSTRAINT `fk_ipc_camera_device_parent`
    FOREIGN KEY (`parent_id`)
    REFERENCES `ipc_camera_device` (`id`)
    ON DELETE SET NULL ON UPDATE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='IPC camera device configuration';
