-- 视频流配置表
CREATE TABLE `xudu_video_device` (
  `id` varchar(36) NOT NULL COMMENT '主键ID',
  `name` varchar(100) DEFAULT NULL COMMENT '视频流名称',
  `username` varchar(50) DEFAULT NULL COMMENT '认证用户名',
  `password` varchar(100) DEFAULT NULL COMMENT '认证密码',
  `ip` varchar(50) DEFAULT NULL COMMENT '设备IP地址',
  `port` varchar(10) DEFAULT NULL COMMENT '设备端口',
  `manufacturer` varchar(50) DEFAULT NULL COMMENT '设备制造商',
  `model` varchar(50) DEFAULT NULL COMMENT '设备型号',
  `type` varchar(20) DEFAULT NULL COMMENT '设备类型(nvr/ipc)',
  `app` varchar(50) DEFAULT 'xudu' COMMENT 'ZLM应用名',
  `status` varchar(20) DEFAULT NULL COMMENT '在线状态',
  `rtsp_url` varchar(500) DEFAULT NULL COMMENT 'RTSP流地址',
  `hls_url` varchar(500) DEFAULT NULL COMMENT 'HLS播放地址',
  `webrtc_url` varchar(500) DEFAULT NULL COMMENT 'WebRTC播放地址',
  `stream` varchar(100) DEFAULT NULL COMMENT 'ZLM流名称',
  `ffmpeg_cmd_key` varchar(100) DEFAULT NULL COMMENT 'FFmpeg转码模板key',
  `video_codec` varchar(50) DEFAULT NULL COMMENT '视频编解码器',
  `audio_codec` varchar(50) DEFAULT NULL COMMENT '音频编解码器',
  `parent_id` varchar(36) DEFAULT NULL COMMENT '父级视频ID(NVR)',
  `channel_no` int DEFAULT NULL COMMENT 'NVR通道数量',
  `serial_number` varchar(64) DEFAULT NULL COMMENT '设备序列号',
  `device_id` varchar(64) DEFAULT NULL COMMENT '设备ID',
  `firmware_version` varchar(64) DEFAULT NULL COMMENT '固件版本',
  `mac_address` varchar(32) DEFAULT NULL COMMENT 'MAC地址',
  `create_by` varchar(50) DEFAULT NULL COMMENT '创建人',
  `create_time` datetime DEFAULT NULL COMMENT '创建时间',
  `update_by` varchar(50) DEFAULT NULL COMMENT '更新人',
  `update_time` datetime DEFAULT NULL COMMENT '更新时间',
  `sys_org_code` varchar(64) DEFAULT NULL COMMENT '所属部门',
  PRIMARY KEY (`id`),
  KEY `idx_stream_app` (`stream`, `app`),
  KEY `idx_ip_port` (`ip`, `port`),
  KEY `idx_status` (`status`),
  KEY `idx_parent` (`parent_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='视频流配置表';

-- 视频码流信息表
CREATE TABLE `xudu_video_stream` (
  `id` varchar(36) NOT NULL COMMENT '主键ID',
  `video_id` varchar(36) NOT NULL COMMENT '关联的视频ID',
  `stream_no` int DEFAULT NULL COMMENT '码流序号(1-主码流/2-子码流)',
  `track_id` int DEFAULT NULL COMMENT '海康trackId',
  `stream_name` varchar(32) DEFAULT NULL COMMENT '码流名称(main/sub/third)',
  `rtsp_url` varchar(500) DEFAULT NULL COMMENT 'RTSP地址',
  `video_codec` varchar(50) DEFAULT NULL COMMENT '视频编码',
  `width` int DEFAULT NULL COMMENT '分辨率宽',
  `height` int DEFAULT NULL COMMENT '分辨率高',
  `frame_rate` int DEFAULT NULL COMMENT '帧率',
  `bit_rate_type` varchar(32) DEFAULT NULL COMMENT '码率类型',
  `bit_rate` int DEFAULT NULL COMMENT '码率',
  `profile` varchar(32) DEFAULT NULL COMMENT 'Profile',
  `gop` int DEFAULT NULL COMMENT 'GOP长度',
  `audio_enabled` tinyint(1) DEFAULT NULL COMMENT '是否含音频',
  `audio_codec` varchar(50) DEFAULT NULL COMMENT '音频编码',
  `audio_sample_rate` int DEFAULT NULL COMMENT '音频采样率',
  `audio_channels` int DEFAULT NULL COMMENT '音频声道数',
  `audio_bit_rate` int DEFAULT NULL COMMENT '音频码率',
  `create_by` varchar(50) DEFAULT NULL COMMENT '创建人',
  `create_time` datetime DEFAULT NULL COMMENT '创建时间',
  `update_by` varchar(50) DEFAULT NULL COMMENT '更新人',
  `update_time` datetime DEFAULT NULL COMMENT '更新时间',
  PRIMARY KEY (`id`),
  KEY `idx_video_stream_video` (`video_id`),
  CONSTRAINT `fk_video_stream_video` FOREIGN KEY (`video_id`) REFERENCES `xudu_video_device`(`id`) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='视频码流信息表';
