-- 视频流配置表
CREATE TABLE `xudu_video_device` (
  `id` varchar(36) NOT NULL COMMENT '主键ID',
  `name` varchar(100) DEFAULT NULL COMMENT '视频流名称',
  `username` varchar(50) DEFAULT NULL COMMENT '认证用户名',
  `password` varchar(100) DEFAULT NULL COMMENT '认证密码',
  `ip` varchar(50) DEFAULT NULL COMMENT '设备IP地址',
  `port` varchar(10) DEFAULT NULL COMMENT '设备端口',
  `manufacturer` varchar(50) DEFAULT NULL COMMENT '设备制造商',
  `model` varchar(50) DEFAULT NULL COMMENT '设备型号',
  `type` varchar(20) DEFAULT NULL COMMENT '设备类型(nvr/ipc)',
  `app` varchar(50) DEFAULT 'xudu' COMMENT 'ZLM应用名',
  `status` varchar(20) DEFAULT NULL COMMENT '在线状态',
  `rtsp_url` varchar(500) DEFAULT NULL COMMENT 'RTSP流地址',
  `hls_url` varchar(500) DEFAULT NULL COMMENT 'HLS播放地址',
  `webrtc_url` varchar(500) DEFAULT NULL COMMENT 'WebRTC播放地址',
  `stream` varchar(100) DEFAULT NULL COMMENT '流名称',
  `ffmpeg_cmd_key` varchar(100) DEFAULT NULL COMMENT 'FFmpeg转码模板key',
  `video_codec` varchar(50) DEFAULT NULL COMMENT '视频编解码器',
  `audio_codec` varchar(50) DEFAULT NULL COMMENT '音频编解码器',
  `create_by` varchar(50) DEFAULT NULL COMMENT '创建人',
  `create_time` datetime DEFAULT NULL COMMENT '创建时间',
  `update_by` varchar(50) DEFAULT NULL COMMENT '更新人',
  `update_time` datetime DEFAULT NULL COMMENT '更新时间',
  `sys_org_code` varchar(64) DEFAULT NULL COMMENT '所属部门',
  PRIMARY KEY (`id`),
  KEY `idx_stream_app` (`stream`, `app`),
  KEY `idx_ip_port` (`ip`, `port`),
  KEY `idx_status` (`status`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='视频流配置表';
