-- POS账户主表
CREATE TABLE `pos_account` (
  `id` varchar(32) NOT NULL COMMENT '主键ID',
  `account_no` varchar(64) NOT NULL COMMENT '账户编号',
  `user_id` varchar(32) DEFAULT NULL COMMENT '关联用户ID',
  `user_name` varchar(64) DEFAULT NULL COMMENT '系统用户名',
  `real_name` varchar(64) DEFAULT NULL COMMENT '真实姓名',
  `gender` varchar(16) DEFAULT NULL COMMENT '性别',
  `phone` varchar(32) DEFAULT NULL COMMENT '手机号',
  `dept_id` varchar(32) DEFAULT NULL COMMENT '部门ID',
  `dept_name` varchar(128) DEFAULT NULL COMMENT '部门名称',
  `position` varchar(64) DEFAULT NULL COMMENT '岗位',
  `id_card_no` varchar(32) DEFAULT NULL COMMENT '身份证号',
  `badge_no` varchar(64) DEFAULT NULL COMMENT '工牌编号',
  `account_type` varchar(32) DEFAULT NULL COMMENT '账户类型',
  `account_level` varchar(32) DEFAULT NULL COMMENT '账户等级',
  `account_status` varchar(32) DEFAULT NULL COMMENT '账户状态',
  `register_channel` varchar(64) DEFAULT NULL COMMENT '注册渠道',
  `register_time` datetime DEFAULT NULL COMMENT '注册时间',
  `last_active_time` datetime DEFAULT NULL COMMENT '最近活跃时间',
  `cash_wallet` decimal(18,2) DEFAULT '0.00' COMMENT '现金钱包',
  `subsidy_wallet` decimal(18,2) DEFAULT '0.00' COMMENT '补贴钱包',
  `gift_wallet` decimal(18,2) DEFAULT '0.00' COMMENT '礼品钱包',
  `frozen_amount` decimal(18,2) DEFAULT '0.00' COMMENT '冻结金额',
  `credit_limit` decimal(18,2) DEFAULT '0.00' COMMENT '授信额度',
  `arrears_amount` decimal(18,2) DEFAULT '0.00' COMMENT '欠费金额',
  `total_balance` decimal(18,2) DEFAULT '0.00' COMMENT '总余额',
  `daily_consumption_limit` decimal(18,2) DEFAULT NULL COMMENT '单日消费限额',
  `single_consumption_limit` decimal(18,2) DEFAULT NULL COMMENT '单笔消费限额',
  `daily_recharge_limit` decimal(18,2) DEFAULT NULL COMMENT '单日充值限额',
  `single_recharge_limit` decimal(18,2) DEFAULT NULL COMMENT '单笔充值限额',
  `auto_recharge_enabled` tinyint(1) DEFAULT '0' COMMENT '自动充值开关',
  `auto_recharge_threshold` decimal(18,2) DEFAULT NULL COMMENT '自动充值阈值',
  `auto_recharge_amount` decimal(18,2) DEFAULT NULL COMMENT '自动充值金额',
  `allow_meal_order` tinyint(1) DEFAULT '1' COMMENT '订餐权限',
  `allow_delivery` tinyint(1) DEFAULT '1' COMMENT '外送权限',
  `allow_self_pickup` tinyint(1) DEFAULT '1' COMMENT '自取权限',
  `bind_devices` json DEFAULT NULL COMMENT '绑定设备',
  `associated_cards` json DEFAULT NULL COMMENT '关联卡号',
  `tags` json DEFAULT NULL COMMENT '标签',
  `loss_reported` tinyint(1) DEFAULT '0' COMMENT '是否挂失',
  `last_loss_report_time` datetime DEFAULT NULL COMMENT '最近挂失时间',
  `last_password_reset_time` datetime DEFAULT NULL COMMENT '最近支付密码重置时间',
  `last_card_reissue_time` datetime DEFAULT NULL COMMENT '最近补卡时间',
  `remark` varchar(512) DEFAULT NULL COMMENT '备注',
  `create_by` varchar(32) DEFAULT NULL COMMENT '创建人',
  `create_time` datetime DEFAULT NULL COMMENT '创建时间',
  `update_by` varchar(32) DEFAULT NULL COMMENT '更新人',
  `update_time` datetime DEFAULT NULL COMMENT '更新时间',
  PRIMARY KEY (`id`),
  UNIQUE KEY `uk_account_no` (`account_no`),
  KEY `idx_user_id` (`user_id`),
  KEY `idx_dept_id` (`dept_id`),
  KEY `idx_account_status` (`account_status`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci COMMENT='POS账户主表';

-- 账户交易流水表
CREATE TABLE `pos_account_transaction` (
  `id` varchar(32) NOT NULL COMMENT '主键ID',
  `account_id` varchar(32) NOT NULL COMMENT '账户ID',
  `account_no` varchar(64) DEFAULT NULL COMMENT '账户编号',
  `transaction_no` varchar(64) NOT NULL COMMENT '流水号',
  `occur_time` datetime DEFAULT NULL COMMENT '发生时间',
  `biz_type` varchar(32) DEFAULT NULL COMMENT '业务类型',
  `direction` varchar(16) DEFAULT NULL COMMENT '收支方向',
  `wallet_type` varchar(16) DEFAULT NULL COMMENT '钱包类型',
  `amount` decimal(18,2) DEFAULT '0.00' COMMENT '交易金额',
  `balance_after` decimal(18,2) DEFAULT '0.00' COMMENT '变动后余额',
  `channel` varchar(128) DEFAULT NULL COMMENT '渠道',
  `biz_no` varchar(128) DEFAULT NULL COMMENT '业务单号',
  `remark` varchar(256) DEFAULT NULL COMMENT '备注',
  `create_by` varchar(32) DEFAULT NULL COMMENT '创建人',
  `create_time` datetime DEFAULT NULL COMMENT '创建时间',
  `update_by` varchar(32) DEFAULT NULL COMMENT '更新人',
  `update_time` datetime DEFAULT NULL COMMENT '更新时间',
  PRIMARY KEY (`id`),
  UNIQUE KEY `uk_transaction_no` (`transaction_no`),
  KEY `idx_account_id` (`account_id`),
  KEY `idx_occur_time` (`occur_time`),
  CONSTRAINT `fk_pos_account_transaction_account_id` FOREIGN KEY (`account_id`) REFERENCES `pos_account` (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci COMMENT='POS账户交易流水';
